apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - port: 3000
    nodePort: 30091
    targetPort: 3000
  selector:
    app: react-frontend-app
  type: NodePort